In [1]:
import numpy as np

import torch.nn as nn
from torch import randn
from torch import tensor
from torch import zeros
from torch import float32
from torch import optim
import torchvision.transforms as trans

from sklearn.preprocessing import MinMaxScaler

import pandas as pd

In [2]:
data = np.array(pd.read_csv('Data/airline-passengers.csv')['Passengers'], dtype=np.float32).reshape(-1, 1)

# scaler = MinMaxScaler()
# scaler.fit(data)
# data = scaler.transform(data)

X = tensor(data)[:111].reshape(-1, 1, 1)
X_test = tensor(data)[109:].reshape(-1, 1, 1)

In [3]:
class RNN(nn.Module):
    def __init__(self):
        super(RNN, self).__init__()
        # self.rlayer = nn.RNN(input_size=1, hidden_size=64, nonlinearity='relu', batch_first=True)
        self.rlayer = nn.LSTM(input_size=1, hidden_size=64, batch_first=True)
        self.linear = nn.Linear(64, 1)
        self.hidden_cell = (zeros(1, 10, 64),
                            zeros(1, 10, 64))
    
    def forward(self, x):
        out, self.hidden_cell = self.rlayer(x, (self.hidden_cell[0].detach(),
                                                self.hidden_cell[1].detach()))
        out = self.linear(out)
        return out
    
model = RNN()

tmp = randn(10, 1, 1)
model(tmp).shape

torch.Size([10, 1, 1])

In [4]:
optimizer = optim.Adam(model.parameters(), lr=0.00001, weight_decay=0.01)
criterion = nn.MSELoss()

In [5]:
bsize = 10

for epoch in range(10000):
    for i in range(100):
        optimizer.zero_grad()
        batch = X[i:i + bsize]
        a = model(batch)
        correct = X[i + 1:i + 1 + bsize]
        
        loss = criterion(a, correct)
        loss.backward(retain_graph=True)
        optimizer.step()
        
    print('Epoch {} Loss {}'.format(epoch, loss.detach()))

Epoch 0 Loss 144510.46875
Epoch 1 Loss 144486.375
Epoch 2 Loss 144459.953125
Epoch 3 Loss 144429.71875
Epoch 4 Loss 144394.15625
Epoch 5 Loss 144350.390625
Epoch 6 Loss 144279.21875
Epoch 7 Loss 144196.21875
Epoch 8 Loss 144135.078125
Epoch 9 Loss 144085.984375
Epoch 10 Loss 144045.15625
Epoch 11 Loss 144009.546875
Epoch 12 Loss 143975.90625
Epoch 13 Loss 143942.78125
Epoch 14 Loss 143911.359375
Epoch 15 Loss 143884.171875
Epoch 16 Loss 143861.40625
Epoch 17 Loss 143841.171875
Epoch 18 Loss 143822.03125
Epoch 19 Loss 143802.359375
Epoch 20 Loss 143779.28125
Epoch 21 Loss 143749.125
Epoch 22 Loss 143713.734375
Epoch 23 Loss 143680.0
Epoch 24 Loss 143648.90625
Epoch 25 Loss 143616.15625
Epoch 26 Loss 143577.375
Epoch 27 Loss 143526.390625
Epoch 28 Loss 143466.078125
Epoch 29 Loss 143410.171875
Epoch 30 Loss 143363.453125
Epoch 31 Loss 143322.59375
Epoch 32 Loss 143284.15625
Epoch 33 Loss 143246.640625
Epoch 34 Loss 143210.34375
Epoch 35 Loss 143173.6875
Epoch 36 Loss 143130.203125
Epoch 

KeyboardInterrupt: 

In [27]:
a

tensor([[[167.1530]],

        [[156.4965]],

        [[136.5062]],

        [[125.8975]],

        [[148.0790]],

        [[150.1277]],

        [[153.4823]],

        [[180.3934]],

        [[157.8033]],

        [[171.8683]]], grad_fn=<AddBackward0>)

In [28]:
correct

tensor([[[158.]],

        [[133.]],

        [[114.]],

        [[140.]],

        [[145.]],

        [[150.]],

        [[178.]],

        [[163.]],

        [[172.]],

        [[178.]]])

In [21]:
criterion(model(X_test[:34]), X_test[1:])

RuntimeError: Expected hidden[0] size (1, 34, 64), got [1, 10, 64]

In [22]:
model(X_test[:34])

RuntimeError: Expected hidden[0] size (1, 34, 64), got [1, 10, 64]

In [23]:
X_test

tensor([[[318.]],

        [[362.]],

        [[348.]],

        [[363.]],

        [[435.]],

        [[491.]],

        [[505.]],

        [[404.]],

        [[359.]],

        [[310.]],

        [[337.]],

        [[360.]],

        [[342.]],

        [[406.]],

        [[396.]],

        [[420.]],

        [[472.]],

        [[548.]],

        [[559.]],

        [[463.]],

        [[407.]],

        [[362.]],

        [[405.]],

        [[417.]],

        [[391.]],

        [[419.]],

        [[461.]],

        [[472.]],

        [[535.]],

        [[622.]],

        [[606.]],

        [[508.]],

        [[461.]],

        [[390.]],

        [[432.]]])